export class DataBase {
    static Produtos =[{
      id: 1,
      nome: 'Painel 3D tijolo branco',
      descricao: 'Painel adesivo Pu. Tamanho: 77x70 cm',
      preco: 32.60,
      categoria:"Adesivos",
      img: "./imgAdesivos/paredeDeT.avif",
      promocao: true,
      precoPromocao: 30.00,
    },
    {
      id: 2,
      nome: 'Adesivo de parede Beija Flor',
      descricao: 'O adesivo de parede é desenvolvido com materiais de excelente qualidade.',
      preco: 45.50, 
      categoria:"Adesivos", 
      img: "./imgAdesivos/adesivo_de_parede_beija_flor_esquerda.avif",
      promocao: false,
    },
    {
      id: 3,
      nome: 'Adesivo piso de banheiro',
      descricao: 'Adesivo antiderrapante infantil Splash com 10 un.',
      preco: 49.50,
      categoria:"Adesivos",
      img: "./imgAdesivos/adesivo_piso_banheiro_antiderrapante_infantil_splash.avif",
      promocao: true,
      precoPromocao: 40.00
    },
    {
      id: 4,
      nome: 'Adesivo de parede quarto frase',
      descricao: 'Adesivo de parede com frase incentivadora.Super fácil de aplicar',
      preco: 45.50,
      categoria:"Adesivos",
      img: "./imgAdesivos/adesivoQuarto.avif",
      promocao: false,
    },
    {
      id: 5,
      nome: 'Adesivo de parede flores e pássaros ',
      descricao: 'Adesivo de parede entardecer flores e passaros.Dimensões: 52x98 cm',
      preco: 60.50,
      categoria:"Adesivos",
      img: "./imgAdesivos/adesivo_de_parede_entardecer_flores_e_passaros.avif",
      promocao: false,
    },
    {
      id: 6,
      nome: 'Adesivo de parede azul Monte Belo',
      descricao: 'Adesivo de azulejo para cozinha com 24un. Tamanho:20x20 cm',
      preco: 80.00,  
      categoria:"Adesivos",
      img: "./imgAdesivos/adesivo_de_azulejo_azul_monte_belo.avif",
      promocao: true,
      precoPromocao: 70.00,
    },
    {
        id: 7,
        nome: 'Cortina longa verde',
        descricao: 'Cortina verde. Dimensões: 1,40x2,80 m',
        preco: 180.00,
        categoria:"Cortinas",
        img: "./imgCortinas/cortinaJ.avif",
        promocao: true,
        precoPromocao: 150.00,
      },
      {
        id: 8,
        nome: 'Cortina longa branca',
        descricao: 'Cortina voil poliéster branco. Dimensões: 1,40x2,80 m',
        preco: 95.99,
        categoria:"Cortinas",
        img: "./imgCortinas/cortinaBranca.avif",
        promocao: false,
      },
      {
        id: 9,
        nome: 'Cortina blackout',
        descricao: 'Cortina blackout corta luz PVC. Dimensões: 1,10x1,30 cm',
        preco: 30.00,
        categoria:"Cortinas",
        img: "./imgCortinas/blackout.avif",
        promocao: false,  
      },
      {
        id: 10,
        nome: 'Tapete para sala',
        descricao: 'O tapete para sala possui estampas geométricas que vão deixar sua casa ainda mais moderna.',
        preco: 359.90,
        categoria:"Tapetes",
        img: "./imgTapetes/tapeteSala.avif",
        promocao: true,
        precoPromocao: 330.00,
      },
      {
        id: 11,
        nome: 'Vela perfumada',
        descricao: 'Vela perfumada cor azul tiffany. Tamanho: 6x5cm',
        preco: 19.90,
        categoria:"Velas",
        img: "./imgVelas/velaPerfumada.avif",
        promocao: false,
      },
      {
        id: 12,
        nome: 'Vela Pilar',
        descricao: 'Vela feita com 100% parafina sem aroma. Alta duração',
        preco: 23.00,
        categoria:"Velas",
        img: "./imgVelas/velaPilar.avif",
        promocao: false,
      },
]
}